import Head from "next/head";
import Nav from "@/components/Nav";
import Image from "next/image";
import ArticlesSection from "@/components/articles/ArticlesSection";
import Footer from "@/components/Footer";
import client from "../../apollo-client";
import Link from "next/link";
import { gql } from "@apollo/client";

const logos = [
    "johns-hopkins-university-logo.png",
    "Paracelsus_Medical_University_Logo.png",
    "lmu_logo.jpg",
    "Logo_Charite.png",
    "Yale_school_of_medicine_logo.jpg",
];

export async function getStaticProps() {
    const { data } = await client.query({
        query: gql`
            query {
                posts {
                    data {
                        id
                        attributes {
                            title
                            publishedAt
                            description
                            slug
                            category {
                                data {
                                    attributes {
                                        name
                                    }
                                }
                            }
                            cover {
                                data {
                                    attributes {
                                        url
                                        alternativeText
                                    }
                                }
                            }
                        }
                    }
                }
            }
        `,
    });

    return {
        props: {
            posts: data.posts,
        },
        revalidate: 120,
    };
}

export default function Home({ posts }) {
    return (
        <>
            <Head>
                <title>Anatomian</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <main className="relative overflow-x-hidden block max-w-full">
                <Nav />
                <div className="container">
                    <header>
                        <div className="flex gap-24 md:pt-8">
                            <div className="pt-10 lg:pt-24 pb-6">
                                <h1 className="font-bold text-3xl md:text-4xl lg:text-6xl xl:text-7.5xl leading-snug pb-3.5 md:pb-6 lg:pb-6 tracking-tight">
                                    Werde ein Ass im Anatomieunterricht
                                </h1>
                                <div className="text-sm font-medium flex gap-6 pb-16 flex-wrap">
                                    <div className="flex gap-2.5">
                                        <Image
                                            width={20}
                                            height={20}
                                            src="/images/check.svg"
                                            alt="Check"
                                        />

                                        <p className="tracking-tight">
                                            10004 hochwertige Abbildungen
                                        </p>
                                    </div>
                                    <div className="flex gap-2.5">
                                        <Image
                                            width={20}
                                            height={20}
                                            src="/images/check.svg"
                                            alt="Check"
                                        />
                                        <p className="tracking-tight">800+ detaillierte Artikel</p>
                                    </div>
                                    <div className="flex gap-2.5">
                                        <Image
                                            width={20}
                                            height={20}
                                            src="/images/check.svg"
                                            alt="Check"
                                        />
                                        <p className="tracking-tight">
                                            Erstellt und geprüft von Medizinern
                                        </p>
                                    </div>
                                </div>
                                <div className="mb-[70px] flex gap-[16px] items-center flex-wrap">
                                    <Link
                                        href="/"
                                        className="py-[11px] px-[30px] lg:px-[62px] bg-[#eee] rounded-[12px] inline-block"
                                    >
                                        <Image
                                            width={136}
                                            height={32}
                                            src="/images/google-play-store.svg"
                                            alt="Google play store"
                                        />
                                    </Link>
                                    <Link
                                        href="/"
                                        className="py-[11px] px-[30px] lg:px-[62px] bg-black rounded-[12px] inline-block"
                                    >
                                        <Image
                                            width={119}
                                            height={32}
                                            src="/images/apple-store.svg"
                                            alt="Apple store"
                                        />
                                    </Link>
                                </div>
                            </div>
                            <div className="max-w-[477px] flex items-center w-full max-md:hidden">
                                <Image
                                    width={323}
                                    height={315}
                                    src="/images/heart-1.png"
                                    alt="Heart"
                                />
                            </div>
                        </div>
                        <div>
                            <p className="text-[#565656] text-lg mb-6">
                                Used by students from these universities
                            </p>
                            <div className=" flex gap-4 items-center flex-wrap">
                                {logos.map((logo) => {
                                    return (
                                        <div className="h-12 w-[150px] relative" key={logo}>
                                            <Image
                                                fill
                                                style={{
                                                    objectFit: "contain",
                                                    height: "100%",
                                                    filter: "grayscale(100%)",
                                                }}
                                                src={`/images/${logo}`}
                                                alt={logo
                                                    .replace(/(_|-)/g, " ")
                                                    .substring(0, logo.lastIndexOf("."))}
                                            />
                                        </div>
                                    );
                                })}
                            </div>
                        </div>
                    </header>
                    <ArticlesSection posts={posts} />
                </div>
            </main>
            <Footer />
        </>
    );
}
