import Head from "next/head";
import Nav from "@/components/Nav";
import Image from "next/image";
import Link from "next/link";
// JOHNS Hopkins University
// Paracelsus medizinische University
// Charite
// Yale school of medicine

const logos = [
    "johns-hopkins-university-logo.png",
    "Paracelsus_Medical_University_Logo.png",
    "lmu_logo.jpg",
    "Logo_Charite.png",
    "Yale_school_of_medicine_logo.jpg",
];

export default function Home() {
    return (
        <>
            <Head>
                <title>Anatomian</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <main className="relative overflow-x-hidden block">
                <Nav />
                <div className="container">
                    <header className="lg:py-8 grid min-h-[90vh] place-items-center">
                        <div className="grid gap-14 grid-cols-12 items-center">
                            <div className="col-span-full md:col-span-8">
                                <h1 className="xl:text-[80px] lg:text-[60px] md:text-[50px] text-[40px] font-bold leading-[1.4] mb-4">
                                    Werde ein Ass im{" "}
                                    <span className="break-words">Anatomieunterricht</span>
                                </h1>
                                <div className="flex gap-[24px] items-center flex-wrap max-w-full">
                                    <Feature text="10004 hochwertige Abbildungen " />
                                    <Feature text="800+ detaillierte Artikel" />
                                    <Feature text="Erstellt und geprüft von Medizinern" />
                                </div>
                                <div className="mt-[64px] flex gap-[16px] items-center flex-wrap">
                                    <Link
                                        href="/"
                                        className="py-[11px] px-[30px] lg:px-[62px] bg-[#eee] rounded-[12px] inline-block"
                                    >
                                        <Image
                                            width={136}
                                            height={32}
                                            src="/images/google-play-store.svg"
                                            alt="Google play store"
                                        />
                                    </Link>
                                    <Link
                                        href="/"
                                        className="py-[11px] px-[30px] lg:px-[62px] bg-black rounded-[12px] inline-block"
                                    >
                                        <Image
                                            width={119}
                                            height={32}
                                            src="/images/apple-store.svg"
                                            alt="Apple store"
                                        />
                                    </Link>
                                </div>
                            </div>
                            <div className="relative aspect-[361/440] col-span-4 hidden md:block">
                                <Image fill src="/images/heart-1.png" alt="Heart" />
                            </div>
                            <div className="col-span-full max-w-full">
                                <p className="text-[#565656] text-lg mb-6">
                                    Used by students from these universities
                                </p>
                                <div className=" flex gap-4 items-center flex-wrap">
                                    {logos.map((logo) => {
                                        return (
                                            <div className="h-12 w-[150px] relative" key={logo}>
                                                <Image
                                                    fill
                                                    style={{
                                                        objectFit: "contain",
                                                        height: "100%",
                                                        filter: "grayscale(100%)",
                                                    }}
                                                    src={`/images/${logo}`}
                                                    alt={logo
                                                        .replace(/(_|-)/g, " ")
                                                        .substring(0, logo.lastIndexOf("."))}
                                                />
                                            </div>
                                        );
                                    })}
                                </div>
                            </div>
                        </div>
                    </header>
                </div>
            </main>
        </>
    );
}

function Feature({ text }) {
    return (
        <div className="flex gap-[10px] items-center">
            <Image width={20} height={20} src="/images/check.svg" alt="Check" />
            <span className="leading-none text-[14px] font-medium">{text}</span>
        </div>
    );
}
